### ISSUE TITLE
can only produces noise

### ISSUE THREAD

**Issue by elemich** [kpthedev/ez-text2video#10]
hallo, i have a nvidia gtx970 with 4gb of vram and 8gb of ram,and with 16 total frames and 8 fps with steps from 10 to 50 at 128x128 (upper resolution crashes) the only output produced is a noisy video similar to this:
![vlcsnap-2024-06-24-17h59m04s483](https://github.com/kpthedev/ez-text2video/assets/20385130/485f65ee-ed9f-409c-9786-f2a547c51928)
![vlcsnap-2024-06-24-17h59m04s483](https://github.com/kpthedev/ez-text2video/assets/20385130/485f65ee-ed9f-409c-9786-f2a547c51928)

a message appeared initially relative to ffmpeg says that vp90 with codec 167 is not supported and i go to /lib/utils.py and changed to mp4v,message is gone,but same result...

this is the only app that works with my settings,i tried comfyui and others at various resolution but they all crashes.

**Comment by kpthedev** [comment]
That's odd. Maybe try installing `ffmpeg` from conda-forge in the conda environment to get the original codecs working.
