### ISSUE TITLE
GPU Error

### ISSUE THREAD

**Issue by swpaxton66** [kpthedev/ez-text2video#5]
Hi.  I am running a 4GB GPU.  I get an error when I try to run the model that the GPU has run out of memory.  I use a stable diffusion model and I am able to set a parameter to allow the model to run with my GPU.  Is it possible to set for this model also?

Thanks

**Comment by swpaxton66** [comment]
This doesn't work with a 4GB GPU as stated.  Any ideas?

**Comment by kpthedev** [comment]
Thank you for pointing this out! I took a look and the model was being duplicated with CPU offloading.

I've just merged a [fix](https://github.com/kpthedev/ez-text2video/pull/6) . Please let me know if it works.
