### ISSUE TITLE
No support for Arc? 

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [kpthedev/ez-text2video#8]
I have an A770, which has 16GB of VRAM, yet I can't seem to be able to enabled GPU acceleration. Cause right now with CPU only, it's pretty unusable, even with a beefy 13600K

**Comment by kpthedev** [comment]
Unfortunately, Hugging Face seems to have limited support for Intel Arc GPUs. You could try running with the `--device cuda` flag (forces using the GPU) to check if it works.
