### ISSUE TITLE
Pip python not found

### ISSUE THREAD

**Issue by KintCark** [kpthedev/ez-text2video#9]
I'm trying to install this on Android termux but I keep getting this error 

Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/miniforge3/envs/t2v/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/ez-text2video/condaenv.ivlgftnj.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
/home/miniforge3/envs/t2v/.tmp6w5kgw1n: line 3: /home/miniforge3/envs/t2v/bin/python: No such file or directory

failed

CondaEnvException: Pip failed

**Comment by kpthedev** [comment]
This is an environment error. I'm not sure if conda works in Termux, but that's where the problem is most likely coming from.
